### ISSUE TITLE
create src/Models/Char.php 

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/rando-php#1]
Create new Model class for characters.
Start from src/Models/Integer.php as "template"

- file: src/Models/Char.php 
- class: Char
- namespace: HiFolks\RandoPhp\Models
- attribtues: min and mix, for lowest char and highest char
- generate: use random_int to extract elements from an array created (for example) with: $ascii_codes = range(48, 57) + range(97, 122);

Better solutions and/or implementations are welcome :)

**Comment by parnus01** [comment]
Can i do this issue for hacktoberfest ?

**Comment by roberto-butti** [comment]
> Can i do this issue for hacktoberfest ?

Sure! Thank you!

**Comment by parnus01** [comment]
@roberto-butti  I already create PR #3

**Comment by roberto-butti** [comment]
> @roberto-butti I already create PR #3

Thank you! Merged!!!!!! 🥳
