### ISSUE TITLE
Cannot call method max() on int

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/rando-php#10]
Resolving conflict name Integer in Randomize.php
If you run phpstan with level 2 you have this kind of Issue:

```
 ------ ----------------------------------
  Line   Models/Sequence.php
 ------ ----------------------------------
  105    Cannot call method max() on int.
 ------ ----------------------------------
```

This is because in Randomize even you you are specifing the name space (
HiFolks\RandoPhp\Models\Integer ) some tools like phpstan and / or PhpStorm raises a warning because they are using Integer as \Interger and not HiFolks\RandoPhp\Models\Integer.

So the first solution that i have, is to use and alias when we refer to Integer class, for example:
```php
use HiFolks\RandoPhp\Models\Integer as ModelInt;
```
and in public static function integer , return a ModelInt instead of Integer.

Probably someone has a better solution... Better solutions are welcome!

**Comment by Rocksheep** [comment]
I'll be picking this up if you don't mind!

**Comment by roberto-butti** [comment]
> I'll be picking this up if you don't mind!

Sure!!! Thank you!

**Comment by roberto-butti** [comment]
@Rocksheep  thank you! Merged!!!

**Comment by Rocksheep** [comment]
You're welcome! 😄
