### ISSUE TITLE
Fix phpdoc in Sequence class, generate() method

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/rando-php#11]
In generate() method we have a phpdoc that says the return value is only array.
There is one scenario (implode) that the method could return a string.

Fix the phpdoc in order to return array|string and not only array

The exact issue is:
```
Method HiFolks\RandoPhp\Models\Sequence::generate() should return array but returns string.
```

**Comment by walish** [comment]
Hi @roberto-butti,
Can I take on this issue?

**Comment by walish** [comment]
It was done in #16 
Could you take a look :D

**Comment by roberto-butti** [comment]
Thank you @walish !!!
