### ISSUE TITLE
Documentation: in readme file add range() example

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/rando-php#2]
IN the readme file, in the "Generate an Integer" section after this example:

``` php
$randomNumber = Randomize::integer()->min(1)->max(6)->generate();
```

add an example with usage with range(1,6) instead of min() and max().
Add also a description line for range() method usage.
From phpdoc:
```
     * Set the range (min and max)
     * Calling range(1,10), it is equivalent of ->min(1)->max(10)
```

**Comment by salonigoyal2309** [comment]
@roberto-butti can i work on this during hacktoberfest 2020 ?

**Comment by roberto-butti** [comment]
@salonigoyal2309 sure! Thank you!

**Comment by sam0hack** [comment]
I made a new commit for this #18

**Comment by salonigoyal2309** [comment]
@sam0hack I was going to work on this issue for hacktoberfest 2020 which started from today 😅 .

**Comment by sam0hack** [comment]
@salonigoyal2309  I didn't check the comments Sorry about that.

**Comment by roberto-butti** [comment]
> @sam0hack I was going to work on this issue for hacktoberfest 2020 which started from today 😅 .

@salonigoyal2309 if you are interested in Documentation / readmefile, I could open some new issues about improve the documentation.
What do you think ?

**Comment by salonigoyal2309** [comment]
@roberto-butti I would love to 😃

**Comment by roberto-butti** [comment]
> @roberto-butti I would love to 😃

@salonigoyal2309 just created #20

**Comment by roberto-butti** [comment]
@sam0hack thank you for your PR! I merged it into master.
