### ISSUE TITLE
Documentation: in readme file add random Char usage example

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/rando-php#20]
Add a section in readme file in order to explain Char usage.
You can start from example files:
https://github.com/Hi-Folks/rando-php/blob/master/examples/RandomChar.php

Explain 3 scenarios:
- Generate random _numeric_ char:
```
Randomize::char()->numeric()->generate();
```
- Generate random alphabetic char:
```
Randomize::char()->alpha()->generate();
```
- Generate randon alphanumeric (alpha or numeric) char:
```
Randomize::char()->alphanumeric()->generate();
```

**Comment by saaheel** [comment]
Shall I make an attempt?

**Comment by salonigoyal2309** [comment]
@roberto-butti on it , thanks

**Comment by roberto-butti** [comment]
> Shall I make an attempt?

It is already assigned.
I can ope new issues for you if you want.
