### ISSUE TITLE
Test: create RandomCharTest

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/rando-php#23]
In order to test the Character random generation, create a test : 
```
class RandomCharTest extends TestCase
```
in tests/RandomCharTest.php.

Things to test:
- generate a random numeric char.
- generate a random alphabetic char.
- generate a random alphanumeric char.

Useful things:
- In order to understand how to call Randomize::char() take a look to examples/RandomChar.php
- If you want to start quickly i suggest you to take a look to _tests/RandomIntegerTest.php_ . I think it is useful to create the structure of the test class.

**Comment by rpaggi** [comment]
Hi, can assign that to me?

**Comment by roberto-butti** [comment]
Sure!!! Thank you

**Comment by phanlyhuynh** [comment]
@roberto-butti Hi, Can i fix this issue? Thanks

**Comment by roberto-butti** [comment]
> @roberto-butti Hi, Can i fix this issue? Thanks

This is assigned to @rpaggi .

@phanlyhuynh  if you want i can add an issue for testing another model (DateTime) and assign to you ...
what do you think ?

**Comment by phanlyhuynh** [comment]
@roberto-butti  Oke. Thanks !!!
Because @rpaggi he wasn't fix it, i fixed it :D

**Comment by roberto-butti** [comment]
> @roberto-butti Oke. Thanks !!!
> Because @rpaggi he wasn't fix it, i fixed it :D

I'm sorry, I'm a little bit confused. Help me to understand better: who has in charge this ?
Just to understand and check if the "Assignees" for this issue is correct or not.

I don't know if it could help, the method to test are _alpha_ , _numeric_ , and _alphanumeric_ .

<img width="1332" alt="Screenshot 2020-10-04 at 08 34 16" src="https://user-images.githubusercontent.com/678434/95008722-aad70000-061c-11eb-8667-fd290aee0253.png">
