### ISSUE TITLE
Add Char in Sequence

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/rando-php#25]
### Some infos on the context:
Sequence model rely on basic model (liike integer) in order to create a sequence of items.
For example
```
Randomize::sequence()->min(1)->max(90)->count(90)->noDuplicates()->generate();
```
it generates a sequence of integer (because integer is the default type):
- count(): number of items
- min(): the min value of the integers
- max(): the max value of the integers
- noDuplicates() the generated items in the sequence must be no duplicated (2,4,1,2 is not valid because the 2 ; instead 5,3,7,6 are valid because unique values)

### Implementation needed:
Add type "Char" in. Sequence, in order to generate a sequence of chars
```
Randomize::sequence()->chars()->alphanumeric()->noDuplicates()->generate();
```

**Comment by bitasterisk** [comment]
can you assign this to me?

**Comment by roberto-butti** [comment]
> can you assign this to me?

Sure!!! Thank you!

**Comment by roberto-butti** [comment]
Thank you @bitasterisk for this high quality PR. I merged your PR.
Thank you also for the unit test and the documentation.
