### ISSUE TITLE
examples: create an example for Random Sequence Char 

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/rando-php#32]
In _examples_ directory create a new _php_ file, named :  _RandomSequenceChar.php_

In this file, I would like to:
- include autoload
- use the class needed (HiFolks\RandoPhp\Randomize)
- write the call to generate() method from Randomize class with _::sequence()_

My suggestion is to take a look from: **examples/basic.php** file where _Randomize::sequence()_ is used , and in Readme file where _Randomize::sequence()->chars()_ is used, for example:
```
$randomChars = Randomize::sequence()->chars()->numeric()->count(10)->generate();
```

WE would need 3 examples:
- numeric chars sequence;
- alphabetical chars sequence;
- alphanumeric chars sequence

**Comment by eruhaji** [comment]
I'd like to work on this issue, can you please assign it me?

**Comment by roberto-butti** [comment]
> I'd like to work on this issue, can you please assign it me?

Sure!!! Thank you!!!
