### ISSUE TITLE
examples: create an example for Random Sequence Integer

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/rando-php#33]
In _examples_ directory create a new _php_ file, named :  _RandomSequenceInteger.php_

In this file, I would like to:
- include autoload
- use the class needed (HiFolks\RandoPhp\Randomize)
- write the call to generate() method from Randomize class with _::integer()_

My suggestion is to take a look from: **examples/basic.php** file where _Randomize::sequence()_ is used , and in Readme file where _Randomize::sequence()_ is used, for example:
```
$randomTombola = Randomize::sequence()->min(1)->max(90)->count(90)->noDuplicates()->generate();
```

We would need 2 examples:
- noDuplicates() usage;
- implode() usage;

**Comment by ferfabricio** [comment]
@roberto-butti  I can work on this task, if possible can you assign to me?

**Comment by roberto-butti** [comment]
> @roberto-butti I can work on this task, if possible can you assign to me?

Sure! Thank you!

**Comment by roberto-butti** [comment]
Hi @ferfabricio are you still working on this ? Or, if you can't work on this, I could assign it to someone else.
Thank you !

Roberto
