### ISSUE TITLE
add asString() method to SEquence

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/rando-php#34]
In Sequence when you call generate() you obtain and array of values (char or integer).
If you use implode() , when you call generate() you obtain a string with values separated by _;_
Add _asString()_ method , that: when you call generate you obtain a string with values concatenated without any separator.
For example calling:
```
$randomChars = Randomize::sequence()->chars()->alphanumeric()->count(10)->asString()->generate();
```
You could obtain something like this:
```
"pks3220x8w"
```

**Comment by paresh27** [comment]
Can you assign me this?

**Comment by roberto-butti** [comment]
> Can you assign me this?

Sure , thank you!!!

**Comment by roberto-butti** [comment]
Thank you for #36 .  Merged!
