### ISSUE TITLE
create src/Models/Float.php

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/rando-php#35]
Create new Model class for float number (with decimals).
Start from src/Models/Integer.php as "template"

- file: src/Models/Float.php 
- class: Float
- namespace: HiFolks\RandoPhp\Models
- attribtues: min (default 0 )and max (default 1), for lowest char and highest char
- attributes: decimals , default (2 decimal)
- generate: genrate a float number considering min, max, decimals attributes;

Example:
```
$float = Randomize::float()->decimal(5)->min(0)->max(100)->generate();
```
It generates something like this: 12.42213

**Comment by jirkavrba** [comment]
Can I take care of this issue?

**Comment by roberto-butti** [comment]
> Can I take care of this issue?

Sure @jirkavrba ! Thank you! Welcome!
Do you have some ideas about how to generate floats in a reliable way?

**Comment by jirkavrba** [comment]
My guess would be to generate an integer within the given min-max range, and then generate the part after comma by using `mt_rand` and `mt_getrandmax`, then tripping it with `round` with the given decimal precision

**Comment by jirkavrba** [comment]
Also, `Float` seems to be a reserved keyword in PHP. I will have to name the class `FloatModel` instead. Do you have any suggestions for a better name?

**Comment by jirkavrba** [comment]
So the final solution seemed to be generating integers and moving the exponent, as generating random floats with `mt_rand` and `mt_getrandmax` couldn't guarantee the required decimals

**Comment by roberto-butti** [comment]
Hi @jirkavrba thank you!
I appreciated also the unit tests. Thank you very much!!!
I opened a new issues , just to have an example about "how to use Float Model" #38

**Comment by jirkavrba** [comment]
I will have a look at it, I also noticed that some tests don't have 100% coverage so I might also improve that

**Comment by roberto-butti** [comment]
> I will have a look at it, I also noticed that some tests don't have 100% coverage so I might also improve that

Great thank you! Please take a look on the issues if you want to add new tests. I opened some issues about adding tests and some of that are already assigned.
