### ISSUE TITLE
examples: create an example for src/Models/FloatModel.php

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/rando-php#38]
In _examples_ directory create a new _php_ file, named :  _RandomInteger.php_

In this file, I would like to:
- include autoload
- use the class needed (HiFolks\RandoPhp\Randomize)
- write the call to generate() method from Randomize class with integer

I would like to show how to use:
- Generate float with min and max ( something like: Randomize::float()->min(0)->max(90)->generate() );
- Generate float with range ( something like: Randomize::float()->range(0.5,1.5)->generate() );
- Generate float using the default ( something like Randomize::float()->generate() ) explaining that the default are 0.0 and 1.0;

My suggestion is to take a look from: **examples/RandomInteger.php** file

**Comment by jirkavrba** [comment]
Please assign me to this one

**Comment by jirkavrba** [comment]
https://github.com/Hi-Folks/rando-php/pull/39

**Comment by roberto-butti** [comment]
Thank you @jirkavrba !
I'm closing this issue.
