### ISSUE TITLE
examples: create an example for Random Boolean

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/rando-php#4]
In _examples_ directory create a new _php_ file, named :  _RandomBoolean.php_

In this file, I would like to:
- include autoload
- use the class needed (HiFolks\RandoPhp\Randomize)
- write the call to generate() method from Randomize class with boolean

My suggestion is to take a look from: **examples/basic.php** file

**Comment by rebelchris** [comment]
@roberto-butti I will have a look at this issue 🤟

**Comment by roberto-butti** [comment]
Thank you. I'm going to assign to you. If you want that your PR counts for Hacktoberfest, remember to open it on 1st october or later 🎉🎉🎉

**Comment by rebelchris** [comment]
@roberto-butti Just created a PR for this issue.
Hopefully, I understood the request correct and this solves the issue. #21

**Comment by roberto-butti** [comment]
Thank you @rebelchris  for your PR!!! I merged it into master!
It was great!
Thank you!!!
