### ISSUE TITLE
Create Latitude Longitude model

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/rando-php#46]
Create new Model class for generating radom Latitude / Longitude coordinates (with decimals).
Start from src/Models/Float.php as "template"

- file: src/Models/LatLong.php 
- class: LatLong
- method array() : you want to generate an array with lat and long like: [41.890242, 12.492326];
- method object() : you want to generate an object like { latitude: 41.890242, longitude: 12.492326];
- method justLatitude() : you want to generate only latitude value like 41.890242;
- method justLongitude() : you want to generate only longitude value like 12.492326;
- namespace: HiFolks\RandoPhp\Models
- generate: genrate a Latitude/Longitude array number;

Example:
```
$latlong = Randomize::latlong()->generate();
```
It generates something like this: [41.890242, 12.492326]

Suggestion:
- use Float model to generate random float;
- considering that latitude is -90 to 90
- considering that longitude is -180 to 180

**Comment by vrabe** [comment]
Hi @roberto-butti , I would like to take it!
Do `array()` and `generate()` do the same thing?

**Comment by roberto-butti** [comment]
> Hi @roberto-butti , I would like to take it!
> Do `array()` and `generate()` do the same thing?

Sure! Thank you!
Exactly, array is the default.

**Comment by roberto-butti** [comment]
Thank you @vrabe  for your high quality PR!
I see that you also add tests, so we are keeping the coverage test to 100%.

Thank you!!!
