### ISSUE TITLE
examples: create an example for src/Models/LatLong.php

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/rando-php#48]
In _examples_ directory create a new _php_ file, named :  _RandomLatLong.php_

In this file, I would like to:
- include autoload
- use the class needed (HiFolks\RandoPhp\Randomize)
- write the call to generate() method from Randomize class with latlong().

I would like to show how to use:
- Generate coordinates in array format. Something like: Randomize::latlong()->asArray()->generate();
- Generate coordinates in object format. Something like: Randomize::latlong()->asObject()->generate();
- Generate latitude in float format. Something like: Randomize::latlong()->asLatitude()->generate();
- Generate longitude in float format. Something like: Randomize::latlong()->asLongitude()->generate();

My suggestion is to take a look from: **examples/RandomFloat.php** file, just to see the structure of the file

**Comment by vrabe** [comment]
Let me do it again!

**Comment by roberto-butti** [comment]
Merged #51 ! thank you!
