### ISSUE TITLE
DateTime Model, max / min default

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/rando-php#49]
In DateTime model set default for min and max. Now it the min and max is hardcoded in attribute declaration.
File: src/Models/DateTime.php

- min the first day of the current year
- max the last day of the current year

Suggestion:
- see [mktime](https://www.php.net/manual/en/function.mktime.php) for creating timestamps in int format.

**Comment by armsasmart** [comment]
Hello, I will do it. Please assign it to me.

**Comment by roberto-butti** [comment]
@armsasmart sure! thank you!
