### ISSUE TITLE
examples: create an example for Random Integer

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/rando-php#5]
In _examples_ directory create a new _php_ file, named :  _RandomInteger.php_

In this file, I would like to:
- include autoload
- use the class needed (HiFolks\RandoPhp\Randomize)
- write the call to generate() method from Randomize class with integer

I would like to show how to use:
- Generate integer with min and max ( something like: Randomize::integer()->min(1)->max(6)->generate() );
- Generate integer with range ( something like: Randomize::integer()->range(1,6)->generate() );
- Generate integere using the default ( something like Randomize::integer()->generate() ) explaining that the default are 0 and 100;

My suggestion is to take a look from: **examples/basic.php** file

**Comment by davidribeiro** [comment]
Hello @roberto-butti can I do this for Hacktoberfest?

**Comment by roberto-butti** [comment]
> Hello @roberto-butti can I do this for Hacktoberfest?

Sure! Thank you!

**Comment by davidribeiro** [comment]
Done in #9 :smile: 
Feel free to give any comments! :+1:

**Comment by roberto-butti** [comment]
> Done in #9 😄
> Feel free to give any comments! 👍

It was great! Thank you!!!
And welcome as contributor ;)

**Comment by davidribeiro** [comment]
No problem, if you need any help just tell me :)
