### ISSUE TITLE
Documentation: in readme file add random Datetime usage example

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/rando-php#52]
Add a section in readme file in order to explain Datetime usage.
You can start from example files:
https://github.com/Hi-Folks/rando-php/blob/master/examples/RandomChar.php

Explain 3 scenarios:
- Generate random datetime with dafault (min: first day of the current year, max: last day of the current year):
```
Randomize::datetime()->generate();
```
- Generate random datetime with specific range:
```
Randomize::datetime()->min('01-01-2020')->max('10-01-2020')->generate();
```
- Generate randon datetime with a specific format:
```
Randomize::datetime()->format('d-M-Y')->generate()
```

**Comment by pret3nti0u5** [comment]
Hey, I would like to work on this. Could you please assign it to me?

**Comment by roberto-butti** [comment]
Sure! Thank you!!!

**Comment by pret3nti0u5** [comment]
Opened a PR #60 . Let me know if you want any changes.

**Comment by roberto-butti** [comment]
This is great @pret3nti0u5 , thank you, PR merged.
