### ISSUE TITLE
Documentation: in readme file add random Float usage example

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/rando-php#53]
Add a section in readme file in order to explain Float usage.
You can start from example files:
https://github.com/Hi-Folks/rando-php/blob/master/examples/RandomChar.php

Explain 2 scenarios:
- Generate random float with default min and max (0.0, 1.0)
```
Randomize::float()->generate();
```
- Generate random float with specific range:
```
Randomize::float()->min(0)->max(90)->generate();
```

**Comment by pret3nti0u5** [comment]
Hey, I would like to work on this issue. Can you assign it to me?

**Comment by pret3nti0u5** [comment]
Added a PR #54 . Let me know if anymore changes are needed.
