### ISSUE TITLE
Char Models: manage lower and upper case

### ISSUE THREAD

**Issue by roberto-butti** [Hi-Folks/rando-php#63]
Now setAlpha sets just lower case char, ascii codes: range(97, 122).
We need to change in _src/Models/Char.php_:
- change method _alpha()_ : needs to include lower range(97, 122) __AND_ upper(69,90)
- implement new method _alphaLower()_ : needs to include just lower range(97, 122)
- implement new method _alphaUpper()_ : needs to include just upper range(69,90)

**Comment by eruhaji** [comment]
I'd like to work on this.

**Comment by eruhaji** [comment]
Just sent PR #65 , please check and let me know.

**Comment by roberto-butti** [comment]
Merged into master and still testing

- [x]  Randomize::char()->alpha()->lower()->generate() produce lower char [a..z];
- [x]  Randomize::char()->alpha()->upper()->generate() produce upper char [A..Z];
- [x]  Randomize::char()->alpha()->generate() it needs to produce lower or upper char [a..z] or [A..Z] (now it produces just lower chars);

**Comment by eruhaji** [comment]
Ok, so if i understand correctly alpha() should return a random alpha with random case

I'll fix it.

**Comment by roberto-butti** [comment]
@xanaDev  merged! thank you!!!
